import moment from "moment";
import i18n from "i18next";

export const getData = () => {
  const cur_month = moment();
  const prev_month = cur_month.clone().add(-1, "M");
  const { t } = i18n;

  return {
    statements: [
      {
        id: 1,
        dateCreated: cur_month.toDate().toString(),
        amount: 1636.2,
        comment: "",
        date: prev_month.date(2).toDate().toString(),
        budgetId: 1,
        accountId: 1,
        budgetName: "Salary",
        accountName: "Main",
      },
      {
        id: 2,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 2,
        accountId: 1,
        date: prev_month.date(2).toDate().toString(),
        amount: 480,
        budgetName: "Apt loan",
        accountName: "Main",
      },
      {
        id: 3,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 8,
        accountId: 1,
        date: prev_month.date(2).toDate().toString(),
        amount: 119,
        budgetName: "Gym",
        accountName: "Main",
      },
      {
        id: 4,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 14,
        accountId: 1,
        date: prev_month.date(2).toDate().toString(),
        amount: 100,
        budgetName: "Short term saving",
        accountName: "Main",
      },
      {
        id: 5,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 13,
        accountId: 1,
        date: prev_month.date(2).toDate().toString(),
        amount: 112,
        budgetName: "Long term saving",
        accountName: "Main",
      },
      {
        id: 6,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 17,
        accountId: 1,
        date: prev_month.date(2).toDate().toString(),
        amount: 710,
        budgetName: "Send to Credit Card",
        accountName: "Main",
      },
      {
        id: 7,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 10,
        accountId: 1,
        date: prev_month.date(8).toDate().toString(),
        amount: 27,
        budgetName: "Electricity",
        accountName: "Main",
      },
      {
        id: 8,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 11,
        accountId: 1,
        date: prev_month.date(8).toDate().toString(),
        amount: 13.6,
        budgetName: "Water",
        accountName: "Main",
      },
      {
        id: 9,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 12,
        accountId: 1,
        date: prev_month.date(8).toDate().toString(),
        amount: 14.2,
        budgetName: "Gas",
        accountName: "Main",
      },
      {
        id: 10,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 5,
        accountId: 1,
        date: prev_month.date(15).toDate().toString(),
        amount: 28.9,
        budgetName: "Internet",
        accountName: "Main",
      },
      {
        id: 11,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 6,
        accountId: 1,
        date: prev_month.date(15).toDate().toString(),
        amount: 9.8,
        budgetName: "Phone",
        accountName: "Main",
      },
      {
        id: 12,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 18,
        accountId: 2,
        date: prev_month.date(7).toDate().toString(),
        amount: 150,
        budgetName: "Cash withdrewal",
        accountName: "Credit card",
      },
      {
        id: 13,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(7).toDate().toString(),
        amount: 36,
        budgetName: "Going out",
        accountName: "Credit card",
        comment: t("demoData.localBar"),
      },
      {
        id: 14,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(8).toDate().toString(),
        amount: 2.7,
        budgetName: "Going out",
        accountName: "Credit card",
        comment: t("demoData.coffee"),
      },
      {
        id: 15,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(14).toDate().toString(),
        amount: 23,
        budgetName: "Going out",
        accountName: "Credit card",
        comment: t("demoData.pool"),
      },
      {
        id: 16,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(21).toDate().toString(),
        amount: 64.9,
        budgetName: "Going out",
        accountName: "Credit card",
        comment: t("demoData.hookah"),
      },
      {
        id: 17,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(21).toDate().toString(),
        amount: 37,
        budgetName: "Going out",
        accountName: "Credit card",
        comment: t("demoData.beers"),
      },
      {
        id: 18,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(28).toDate().toString(),
        amount: 46,
        budgetName: "Going out",
        accountName: "Credit card",
        comment: t("demoData.bowling"),
      },
      {
        id: 19,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 16,
        accountId: 3,
        date: prev_month.date(5).toDate().toString(),
        amount: 30,
        budgetName: "Kids allowance",
        accountName: "Cash",
      },
      {
        id: 20,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 16,
        accountId: 3,
        date: prev_month.date(15).toDate().toString(),
        amount: 80,
        budgetName: "Kids allowance",
        accountName: "Cash",
      },
      {
        id: 21,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 16,
        accountId: 3,
        date: prev_month.date(26).toDate().toString(),
        amount: 20,
        budgetName: "Kids allowance",
        accountName: "Cash",
      },
      {
        id: 22,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(1).toDate().toString(),
        amount: 16.3,
        budgetName: "Groceries",
        accountName: "Credit card",
        comment: t("demoData.vegetables"),
      },
      {
        id: 23,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(8).toDate().toString(),
        amount: 16.8,
        budgetName: "Groceries",
        accountName: "Credit card",
        comment: t("demoData.steaks"),
      },
      {
        id: 24,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(10).toDate().toString(),
        amount: 34.1,
        budgetName: "Groceries",
        accountName: "Credit card",
      },
      {
        id: 25,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(17).toDate().toString(),
        amount: 4.5,
        budgetName: "Groceries",
        accountName: "Credit card",
      },
      {
        id: 26,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(18).toDate().toString(),
        amount: 61.9,
        budgetName: "Groceries",
        accountName: "Credit card",
        comment: t("demoData.wholeSale"),
      },
      {
        id: 27,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 4,
        accountId: 2,
        date: prev_month.date(20).toDate().toString(),
        amount: 42,
        budgetName: "Alcohol",
        accountName: "Credit card",
        comment: t("demoData.lagavulin"),
      },
      {
        id: 28,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 4,
        accountId: 2,
        date: prev_month.date(22).toDate().toString(),
        amount: 21.4,
        budgetName: "Alcohol",
        accountName: "Credit card",
        comment: t("demoData.jimBeam"),
      },
      {
        id: 29,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(22).toDate().toString(),
        amount: 40.3,
        budgetName: "Groceries",
        accountName: "Credit card",
        comment: t("demoData.partySnacks"),
      },
      {
        id: 30,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(27).toDate().toString(),
        amount: 39.5,
        budgetName: "Groceries",
        accountName: "Credit card",
      },
      {
        id: 31,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(1).toDate().toString(),
        amount: 56.8,
        budgetName: "Going out",
        accountName: "Credit card",
        comment: t("demoData.workParty"),
      },
      {
        id: 32,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 2,
        accountId: 1,
        date: cur_month.date(2).toDate().toString(),
        amount: 480,
        budgetName: "Apt loan",
        accountName: "Main",
      },
      {
        id: 33,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 1,
        accountId: 1,
        date: cur_month.date(1).toDate().toString(),
        amount: 1635.8,
        budgetName: "Salary",
        accountName: "Main",
      },
      {
        id: 34,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 10,
        accountId: 1,
        date: cur_month.date(7).toDate().toString(),
        amount: 11.5,
        budgetName: "Electricity",
        accountName: "Main",
      },
      {
        id: 35,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 11,
        accountId: 1,
        date: cur_month.date(7).toDate().toString(),
        amount: 16.3,
        budgetName: "Water",
        accountName: "Main",
      },
      {
        id: 36,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 12,
        accountId: 1,
        date: cur_month.date(7).toDate().toString(),
        amount: 15.8,
        budgetName: "Gas",
        accountName: "Main",
      },
      {
        id: 37,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 5,
        accountId: 1,
        date: cur_month.date(7).toDate().toString(),
        amount: 28.9,
        budgetName: "Internet",
        accountName: "Main",
      },
      {
        id: 38,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 6,
        accountId: 1,
        date: cur_month.date(7).toDate().toString(),
        amount: 10.3,
        budgetName: "Phone",
        accountName: "Main",
      },
      {
        id: 39,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 14,
        accountId: 1,
        date: cur_month.date(7).toDate().toString(),
        amount: 100,
        budgetName: "Short term saving",
        accountName: "Main",
      },
      {
        id: 40,
        dateCreated: cur_month.toDate().toString(),
        amount: 345,
        date: cur_month.date(26).toDate().toString(),
        budgetId: 13,
        accountId: 1,
        budgetName: "Long term saving",
        accountName: "Main",
      },
      {
        id: 41,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 17,
        accountId: 1,
        date: cur_month.date(7).toDate().toString(),
        amount: 660,
        budgetName: "Send to Credit Card",
        accountName: "Main",
      },
      {
        id: 42,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 18,
        accountId: 2,
        date: cur_month.date(8).toDate().toString(),
        amount: 150,
        budgetName: "Cash withdrewal",
        accountName: "Credit card",
      },
      {
        id: 43,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 16,
        accountId: 3,
        date: cur_month.date(8).toDate().toString(),
        amount: 40,
        budgetName: "Kids allowance",
        accountName: "Cash",
      },
      {
        id: 44,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 16,
        accountId: 3,
        date: cur_month.date(15).toDate().toString(),
        amount: 35,
        budgetName: "Kids allowance",
        accountName: "Cash",
      },
      {
        id: 45,
        dateCreated: cur_month.toDate().toString(),
        amount: 45,
        date: cur_month.date(26).toDate().toString(),
        budgetId: 16,
        accountId: 3,
        budgetName: "Kids allowance",
        accountName: "Cash",
      },
      {
        id: 46,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 15,
        accountId: 2,
        date: cur_month.date(2).toDate().toString(),
        amount: 40.6,
        budgetName: "Going out",
        accountName: "Credit card",
        comment: t("demoData.beers"),
      },
      {
        id: 47,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 15,
        accountId: 2,
        date: cur_month.date(8).toDate().toString(),
        amount: 3.6,
        budgetName: "Going out",
        accountName: "Credit card",
        comment: t("demoData.coffee"),
      },
      {
        id: 48,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 15,
        accountId: 2,
        date: cur_month.date(9).toDate().toString(),
        amount: 19.3,
        budgetName: "Going out",
        accountName: "Credit card",
        comment: t("demoData.pizza"),
      },
      {
        id: 49,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 3,
        accountId: 2,
        date: cur_month.date(3).toDate().toString(),
        amount: 16.4,
        budgetName: "Groceries",
        accountName: "Credit card",
        comment: t("demoData.market"),
      },
      {
        id: 50,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 3,
        accountId: 2,
        date: cur_month.date(8).toDate().toString(),
        amount: 36.8,
        budgetName: "Groceries",
        accountName: "Credit card",
      },
      {
        id: 51,
        dateCreated: cur_month.toDate().toString(),
        budgetId: 3,
        accountId: 2,
        date: cur_month.date(12).toDate().toString(),
        amount: 18.3,
        budgetName: "Groceries",
        accountName: "Credit card",
        comment: t("demoData.meat"),
      },
    ],
    budgets: [
      {
        id: 1,
        dateCreated: cur_month.toDate().toString(),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.salary"),
        isEssential: true,
        amounts: [
          {
            amount: "1630",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 10,
        expectOneStatement: true,
      },
      {
        id: 2,
        dateCreated: cur_month.toDate().toString(),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.aptLoan"),
        isEssential: true,
        amounts: [
          {
            amount: "480",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: true,
      },
      {
        id: 3,
        dateCreated: cur_month.toDate().toString(),
        parentId: 0,
        fromAccountId: 2,
        toAccountId: 0,
        name: t("demoData.groceries"),
        isEssential: true,
        amounts: [
          {
            amount: "cur_month.getWeekdaysInMonth(6)*50",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 4,
        dateCreated: cur_month.toDate().toString(),
        parentId: 3,
        fromAccountId: 2,
        toAccountId: 0,
        name: t("demoData.alcohol"),
        isEssential: false,
        amounts: [
          {
            amount: "60",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 5,
        dateCreated: cur_month.toDate().toString(),
        parentId: 9,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.internet"),
        isEssential: true,
        amounts: [
          {
            amount: "29",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 6,
        dateCreated: cur_month.toDate().toString(),
        parentId: 9,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.phone"),
        isEssential: true,
        amounts: [
          {
            amount: "15",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 7,
        dateCreated: cur_month.toDate().toString(),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.sport"),
        isEssential: true,
        amounts: [],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 8,
        dateCreated: cur_month.toDate().toString(),
        parentId: 7,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.gym"),
        isEssential: false,
        amounts: [
          {
            amount: "119",
            frequency: 3,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 9,
        dateCreated: cur_month.toDate().toString(),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.bills"),
        isEssential: true,
        amounts: [],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 10,
        dateCreated: cur_month.toDate().toString(),
        parentId: 9,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.electricity"),
        isEssential: true,
        amounts: [
          {
            amount: "30",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: true,
      },
      {
        id: 11,
        dateCreated: cur_month.toDate().toString(),
        parentId: 9,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.water"),
        isEssential: true,
        amounts: [
          {
            amount: "15",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: true,
      },
      {
        id: 12,
        dateCreated: cur_month.toDate().toString(),
        parentId: 9,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.gas"),
        isEssential: true,
        amounts: [
          {
            amount: "20",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: true,
      },
      {
        id: 13,
        dateCreated: cur_month.toDate().toString(),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.longTermSaving"),
        isEssential: false,
        amounts: [
          {
            amount:
              "cur_month.account(1).openingBalance - cur_month.account(1).totalSpending - cur_month.account(1).totalToOtherAccount - cur_month.getItem(14)",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 40,
        expectOneStatement: false,
      },
      {
        id: 14,
        dateCreated: cur_month.toDate().toString(),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.shortTermSaving"),
        isEssential: false,
        amounts: [
          {
            amount: "100",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 40,
        expectOneStatement: true,
      },
      {
        id: 15,
        dateCreated: cur_month.toDate().toString(),
        parentId: 0,
        fromAccountId: 2,
        toAccountId: 0,
        name: t("demoData.goingOut"),
        isEssential: false,
        amounts: [
          {
            amount: "250",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 16,
        dateCreated: cur_month.toDate().toString(),
        parentId: 0,
        fromAccountId: 3,
        toAccountId: 0,
        name: t("demoData.kidsAllowance"),
        isEssential: false,
        amounts: [
          {
            amount: "150",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 17,
        dateCreated: cur_month.toDate().toString(),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 2,
        name: t("demoData.sendToCC"),
        isEssential: true,
        amounts: [
          {
            amount:
              "cur_month.account(2).totalSpendings + cur_month.account(2).totalToOtherAccount",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 50,
        expectOneStatement: false,
      },
      {
        id: 18,
        dateCreated: cur_month.toDate().toString(),
        parentId: 0,
        fromAccountId: 2,
        toAccountId: 3,
        name: t("demoData.cashWithdrawal"),
        isEssential: true,
        amounts: [
          {
            amount: "cur_month.account(3).totalSpendings",
            frequency: 1,
            startDate: prev_month.date(1).toDate().toString(),
          },
        ],
        overrides: [],
        type: 50,
        expectOneStatement: true,
      },
    ],
    accounts: [
      {
        id: 1,
        dateCreated: cur_month.toDate().toString(),
        name: t("demoData.main"),
        leftFromPrevMonth: [
          {
            amount: 43,
            month: prev_month.date(1).toDate().toString(),
          },
          {
            amount: 64.7,
            month: cur_month.date(1).toDate().toString(),
          },
        ],
      },
      {
        id: 2,
        dateCreated: cur_month.toDate().toString(),
        name: t("demoData.creditCard"),
        leftFromPrevMonth: [
          {
            amount: 16.8,
            month: cur_month.date(1).toDate().toString(),
          },
        ],
      },
      {
        id: 3,
        dateCreated: cur_month.toDate().toString(),
        name: t("demoData.cash"),
        leftFromPrevMonth: [
          {
            amount: 20,
            month: cur_month.date(1).toDate().toString(),
          },
        ],
      },
    ],
  };
};
