import moment from "moment";
import i18n from "i18next";
import { DATE_FORMAT } from "./dateHelper";

export const getData = () => {
  const cur_month = moment();
  const prev_month = cur_month.clone().add(-1, "M");
  const { t } = i18n;

  return {
    statements: [
      {
        id: 1,
        dateCreated: cur_month.format(DATE_FORMAT),
        amount: 1636.2,
        comment: "",
        date: prev_month.date(2).format(DATE_FORMAT),
        budgetId: 1,
        accountId: 1,
      },
      {
        id: 2,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 2,
        accountId: 1,
        date: prev_month.date(2).format(DATE_FORMAT),
        amount: 480,
      },
      {
        id: 3,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 8,
        accountId: 1,
        date: prev_month.date(2).format(DATE_FORMAT),
        amount: 119,
      },
      {
        id: 4,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 14,
        accountId: 1,
        date: prev_month.date(2).format(DATE_FORMAT),
        amount: 100,
      },
      {
        id: 5,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 13,
        accountId: 1,
        date: prev_month.date(2).format(DATE_FORMAT),
        amount: 2,
      },
      {
        id: 6,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 17,
        accountId: 1,
        date: prev_month.date(2).format(DATE_FORMAT),
        amount: 780,
      },
      {
        id: 7,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 10,
        accountId: 1,
        date: prev_month.date(8).format(DATE_FORMAT),
        amount: 27,
      },
      {
        id: 8,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 11,
        accountId: 1,
        date: prev_month.date(8).format(DATE_FORMAT),
        amount: 13.6,
      },
      {
        id: 9,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 12,
        accountId: 1,
        date: prev_month.date(8).format(DATE_FORMAT),
        amount: 14.2,
      },
      {
        id: 10,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 5,
        accountId: 1,
        date: prev_month.date(15).format(DATE_FORMAT),
        amount: 28.9,
      },
      {
        id: 11,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 6,
        accountId: 1,
        date: prev_month.date(15).format(DATE_FORMAT),
        amount: 9.8,
      },
      {
        id: 12,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 18,
        accountId: 2,
        date: prev_month.date(7).format(DATE_FORMAT),
        amount: 170,
      },
      {
        id: 13,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(7).format(DATE_FORMAT),
        amount: 36,
        comment: t("demoData.localBar"),
      },
      {
        id: 14,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(8).format(DATE_FORMAT),
        amount: 2.7,
        comment: t("demoData.coffee"),
      },
      {
        id: 15,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(14).format(DATE_FORMAT),
        amount: 23,
        comment: t("demoData.pool"),
      },
      {
        id: 16,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(21).format(DATE_FORMAT),
        amount: 64.9,
        comment: t("demoData.hookah"),
      },
      {
        id: 17,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(21).format(DATE_FORMAT),
        amount: 37,
        comment: t("demoData.beers"),
      },
      {
        id: 18,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(28).format(DATE_FORMAT),
        amount: 46,
        comment: t("demoData.bowling"),
      },
      {
        id: 19,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 16,
        accountId: 3,
        date: prev_month.date(5).format(DATE_FORMAT),
        amount: 30,
      },
      {
        id: 20,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 16,
        accountId: 3,
        date: prev_month.date(15).format(DATE_FORMAT),
        amount: 80,
      },
      {
        id: 21,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 16,
        accountId: 3,
        date: prev_month.date(26).format(DATE_FORMAT),
        amount: 20,
      },
      {
        id: 22,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(1).format(DATE_FORMAT),
        amount: 16.3,
        comment: t("demoData.vegetables"),
      },
      {
        id: 23,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(8).format(DATE_FORMAT),
        amount: 16.8,
        comment: t("demoData.steaks"),
      },
      {
        id: 24,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(10).format(DATE_FORMAT),
        amount: 34.1,
      },
      {
        id: 25,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(17).format(DATE_FORMAT),
        amount: 4.5,
      },
      {
        id: 26,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(18).format(DATE_FORMAT),
        amount: 61.9,
        comment: t("demoData.wholeSale"),
      },
      {
        id: 27,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 4,
        accountId: 2,
        date: prev_month.date(20).format(DATE_FORMAT),
        amount: 42,
        comment: t("demoData.lagavulin"),
      },
      {
        id: 28,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 4,
        accountId: 2,
        date: prev_month.date(22).format(DATE_FORMAT),
        amount: 21.4,
        comment: t("demoData.jimBeam"),
      },
      {
        id: 29,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(22).format(DATE_FORMAT),
        amount: 40.3,
        comment: t("demoData.partySnacks"),
      },
      {
        id: 30,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 3,
        accountId: 2,
        date: prev_month.date(27).format(DATE_FORMAT),
        amount: 39.5,
      },
      {
        id: 31,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 15,
        accountId: 2,
        date: prev_month.date(1).format(DATE_FORMAT),
        amount: 56.8,
        comment: t("demoData.workParty"),
      },
      {
        id: 32,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 2,
        accountId: 1,
        date: cur_month.date(2).format(DATE_FORMAT),
        amount: 480,
      },
      {
        id: 33,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 1,
        accountId: 1,
        date: cur_month.date(1).format(DATE_FORMAT),
        amount: 1635.8,
      },
      {
        id: 34,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 10,
        accountId: 1,
        date: cur_month.date(7).format(DATE_FORMAT),
        amount: 11.5,
      },
      {
        id: 35,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 11,
        accountId: 1,
        date: cur_month.date(7).format(DATE_FORMAT),
        amount: 16.3,
      },
      {
        id: 36,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 12,
        accountId: 1,
        date: cur_month.date(7).format(DATE_FORMAT),
        amount: 15.8,
      },
      {
        id: 37,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 5,
        accountId: 1,
        date: cur_month.date(7).format(DATE_FORMAT),
        amount: 28.9,
      },
      {
        id: 38,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 6,
        accountId: 1,
        date: cur_month.date(7).format(DATE_FORMAT),
        amount: 10.3,
      },
      {
        id: 39,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 14,
        accountId: 1,
        date: cur_month.date(7).format(DATE_FORMAT),
        amount: 100,
      },
      {
        id: 40,
        dateCreated: cur_month.format(DATE_FORMAT),
        amount: 255,
        date: cur_month.date(26).format(DATE_FORMAT),
        budgetId: 13,
        accountId: 1,
      },
      {
        id: 41,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 17,
        accountId: 1,
        date: cur_month.date(7).format(DATE_FORMAT),
        amount: 730,
      },
      {
        id: 42,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 18,
        accountId: 2,
        date: cur_month.date(8).format(DATE_FORMAT),
        amount: 170,
      },
      {
        id: 43,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 16,
        accountId: 3,
        date: cur_month.date(8).format(DATE_FORMAT),
        amount: 40,
      },
      {
        id: 44,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 16,
        accountId: 3,
        date: cur_month.date(15).format(DATE_FORMAT),
        amount: 35,
      },
      {
        id: 45,
        dateCreated: cur_month.format(DATE_FORMAT),
        amount: 45,
        date: cur_month.date(26).format(DATE_FORMAT),
        budgetId: 16,
        accountId: 3,
      },
      {
        id: 46,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 15,
        accountId: 2,
        date: cur_month.date(2).format(DATE_FORMAT),
        amount: 40.6,
        comment: t("demoData.beers"),
      },
      {
        id: 47,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 15,
        accountId: 2,
        date: cur_month.date(8).format(DATE_FORMAT),
        amount: 3.6,
        comment: t("demoData.coffee"),
      },
      {
        id: 48,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 15,
        accountId: 2,
        date: cur_month.date(9).format(DATE_FORMAT),
        amount: 19.3,
        comment: t("demoData.pizza"),
      },
      {
        id: 49,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 3,
        accountId: 2,
        date: cur_month.date(3).format(DATE_FORMAT),
        amount: 16.4,
        comment: t("demoData.market"),
      },
      {
        id: 50,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 3,
        accountId: 2,
        date: cur_month.date(8).format(DATE_FORMAT),
        amount: 36.8,
      },
      {
        id: 51,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 3,
        accountId: 2,
        date: cur_month.date(12).format(DATE_FORMAT),
        amount: 18.3,
        comment: t("demoData.meat"),
      },
      {
        id: 52,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 19,
        accountId: 1,
        date: prev_month.date(13).format(DATE_FORMAT),
        amount: 20,
        comment: t("demoData.borrow"),
      },
      {
        id: 53,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 19,
        accountId: 2,
        date: cur_month.date(7).format(DATE_FORMAT),
        amount: 15.4,
        comment: t("demoData.parking"),
      },
      {
        id: 54,
        dateCreated: cur_month.format(DATE_FORMAT),
        budgetId: 19,
        accountId: 3,
        date: cur_month.date(16).format(DATE_FORMAT),
        amount: 9.6,
        comment: t("demoData.parking"),
      },
    ],
    budgets: [
      {
        id: 1,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.salary"),
        isEssential: true,
        amounts: [
          {
            amount: "1630",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 10,
        expectOneStatement: true,
      },
      {
        id: 2,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.aptLoan"),
        isEssential: true,
        amounts: [
          {
            amount: "480",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 30,
        expectOneStatement: true,
      },
      {
        id: 3,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 2,
        toAccountId: 0,
        name: t("demoData.groceries"),
        isEssential: true,
        amounts: [
          {
            amount: "cur_month.getWeekdaysInMonth(6)*50",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 4,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 3,
        fromAccountId: 2,
        toAccountId: 0,
        name: t("demoData.alcohol"),
        isEssential: false,
        amounts: [
          {
            amount: "60",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 5,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 9,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.internet"),
        isEssential: true,
        amounts: [
          {
            amount: "29",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 6,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 9,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.phone"),
        isEssential: true,
        amounts: [
          {
            amount: "15",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 7,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.sport"),
        isEssential: true,
        amounts: [],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 8,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 7,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.gym"),
        isEssential: false,
        amounts: [
          {
            amount: "119",
            frequency: 3,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 9,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.bills"),
        isEssential: true,
        amounts: [],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 10,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 9,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.electricity"),
        isEssential: true,
        amounts: [
          {
            amount: "30",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: true,
      },
      {
        id: 11,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 9,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.water"),
        isEssential: true,
        amounts: [
          {
            amount: "15",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: true,
      },
      {
        id: 12,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 9,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.gas"),
        isEssential: true,
        amounts: [
          {
            amount: "20",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: true,
      },
      {
        id: 13,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.longTermSaving"),
        isEssential: false,
        amounts: [
          {
            amount:
              "cur_month.getOpeningBalance(1) - cur_month.getTotalSpending(1) - cur_month.getTotalLoanReturn(1) - cur_month.getTotalToOtherAccount(1) - cur_month.getItem(14)",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 40,
        expectOneStatement: false,
      },
      {
        id: 14,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 0,
        name: t("demoData.shortTermSaving"),
        isEssential: false,
        amounts: [
          {
            amount: "100",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 40,
        expectOneStatement: true,
      },
      {
        id: 15,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 2,
        toAccountId: 0,
        name: t("demoData.goingOut"),
        isEssential: false,
        amounts: [
          {
            amount: "250",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 16,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 3,
        toAccountId: 0,
        name: t("demoData.kidsAllowance"),
        isEssential: false,
        amounts: [
          {
            amount: "150",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
      {
        id: 17,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 1,
        toAccountId: 2,
        name: t("demoData.sendToCC"),
        isEssential: true,
        amounts: [
          {
            amount:
              "cur_month.getTotalSpending(2) + cur_month.getTotalLoanReturn(2) + cur_month.getTotalSaving(2) + cur_month.getTotalToOtherAccount(2)",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 50,
        expectOneStatement: false,
      },
      {
        id: 18,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 2,
        toAccountId: 3,
        name: t("demoData.cashWithdrawal"),
        isEssential: true,
        amounts: [
          {
            amount:
              "cur_month.getTotalSpending(3) + cur_month.getTotalLoanReturn(3) + cur_month.getTotalSaving(3)",
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 50,
        expectOneStatement: true,
      },
      {
        id: 19,
        dateCreated: cur_month.format(DATE_FORMAT),
        parentId: 0,
        fromAccountId: 0,
        toAccountId: 0,
        name: t("demoData.unplanned"),
        isEssential: true,
        amounts: [
          {
            amount: "40",
            fromAccountId: 1,
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
          {
            amount: "50",
            fromAccountId: 2,
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
          {
            amount: "20",
            fromAccountId: 3,
            frequency: 1,
            startDate: prev_month.date(1).format(DATE_FORMAT),
          },
        ],
        overrides: [],
        type: 20,
        expectOneStatement: false,
      },
    ],
    accounts: [
      {
        id: 1,
        dateCreated: cur_month.format(DATE_FORMAT),
        name: t("demoData.main"),
        leftFromPrevMonth: [
          {
            amount: 43,
            month: prev_month.date(1).format(DATE_FORMAT),
          },
          {
            amount: 84.7,
            month: cur_month.date(1).format(DATE_FORMAT),
          },
        ],
      },
      {
        id: 2,
        dateCreated: cur_month.format(DATE_FORMAT),
        name: t("demoData.creditCard"),
        leftFromPrevMonth: [
          {
            amount: 66.8,
            month: cur_month.date(1).format(DATE_FORMAT),
          },
        ],
      },
      {
        id: 3,
        dateCreated: cur_month.format(DATE_FORMAT),
        name: t("demoData.cash"),
        leftFromPrevMonth: [
          {
            amount: 40,
            month: cur_month.date(1).format(DATE_FORMAT),
          },
        ],
      },
    ],
  };
};
